---
language: ruby
rvm:
  - 2.3.1

before_install:
  - openssl aes-256-cbc -K $encrypted_322ef0696a2c_key -iv $encrypted_322ef0696a2c_iv
    -in id_rsa.enc -out id_rsa -d

install:
  - bundle install

script:
  - bundle exec jekyll build
