source 'https://rubygems.org'
gem 'jekyll', '~> 3.3.1'
gem 'jekyll-sitemap', '~> 0.12.0'
gem 'jekyll-paginate', '~> 1.1.0'
gem 'jekyll-seo-tag', '~> 2.1.0'
gem 'jekyll-archives', '~> 2.1'
gem 'rake', '~> 12.0'
